In [51]:
from tensorflow.keras.preprocessing.text import one_hot


In [52]:
### sentences
sent= [ 'the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [53]:
##Define the vocablury
voc_size =10000

In [54]:
## one hot representation
one_hot_repr= [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3563, 2731, 3692, 8781],
 [3563, 2731, 3692, 5140],
 [3563, 6362, 3692, 692],
 [1641, 7772, 1121, 4492, 4497],
 [1641, 7772, 1121, 4492, 9173],
 [4935, 3563, 2199, 3692, 9408],
 [1498, 5919, 9281, 4492]]

In [55]:
##word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [56]:
import numpy as np


In [57]:
sent_length =8
embedded_docs = pad_sequences(one_hot_repr,padding='pre' ,maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3563 2731 3692 8781]
 [   0    0    0    0 3563 2731 3692 5140]
 [   0    0    0    0 3563 6362 3692  692]
 [   0    0    0 1641 7772 1121 4492 4497]
 [   0    0    0 1641 7772 1121 4492 9173]
 [   0    0    0 4935 3563 2199 3692 9408]
 [   0    0    0    0 1498 5919 9281 4492]]


In [58]:
##feature representation
dim =10


In [59]:
model=Sequential()
model.add(Embedding(voc_size, dim,input_length =sent_length))
model.compile('adam','mse')

In [60]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [61]:
embedded_docs[0]

array([   0,    0,    0,    0, 3563, 2731, 3692, 8781], dtype=int32)

In [62]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step


array([[[-2.59358641e-02, -3.07432655e-02, -3.49365175e-04,
         -2.00333595e-02, -4.85338271e-04, -4.90854383e-02,
          5.37674502e-03, -6.00386411e-04, -2.21681837e-02,
          1.60223953e-02],
        [-2.59358641e-02, -3.07432655e-02, -3.49365175e-04,
         -2.00333595e-02, -4.85338271e-04, -4.90854383e-02,
          5.37674502e-03, -6.00386411e-04, -2.21681837e-02,
          1.60223953e-02],
        [-2.59358641e-02, -3.07432655e-02, -3.49365175e-04,
         -2.00333595e-02, -4.85338271e-04, -4.90854383e-02,
          5.37674502e-03, -6.00386411e-04, -2.21681837e-02,
          1.60223953e-02],
        [-2.59358641e-02, -3.07432655e-02, -3.49365175e-04,
         -2.00333595e-02, -4.85338271e-04, -4.90854383e-02,
          5.37674502e-03, -6.00386411e-04, -2.21681837e-02,
          1.60223953e-02],
        [-4.03604656e-03,  4.79942597e-02,  4.47563417e-02,
         -8.09954479e-03, -8.26889277e-03,  4.74147834e-02,
          1.06966719e-02, -2.32284665e-02,  1.543502